# Generated by Django 4.2.11 on 2026-03-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersearch',
            name='winddirection',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weathersearch',
            name='windspeed',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
